
name: Build Debian Packages
on:
  schedule:
    - cron: '37 5 * * *'
  push:
    branches:
      - force-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          last_commit_date=$(git log -1 --format=%cd --date=unix)
          last_day=$(date -d '-1 day' +%s)

          if [ "${last_commit_date}" -lt "${last_day}" ]; then
            echo "Nothig new to build."
            echo "Last commit:"
            git log -1 --format='%C(auto)%h (%cd) - %s' --date=relative
            exit 0
          fi
          
          sudo modprobe binfmt_misc
          sudo ./build-docker.sh

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-image
          path: deploy/*.zip

